Organismos:
  type: entity
  table: organismos
  fields:
    idOrganismo:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: id_organismo
      generator:
        strategy: SEQUENCE
    rif:
      type: string
      length: 12
      fixed: false
      nullable: false
    nombreOrganismo:
      type: string
      length: 60
      fixed: false
      nullable: false
      column: nombre_organismo
    sector:
      type: string
      length: 20
      fixed: false
      nullable: false
  lifecycleCallbacks: {  }
