Perfiles:
  type: entity
  table: perfiles
  fields:
    idPerfil:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: id_perfil
      generator:
        strategy: SEQUENCE
    perfil:
      type: string
      length: 50
      fixed: false
      nullable: false
    descripcionPerfil:
      type: string
      length: 200
      fixed: false
      nullable: false
      column: descripcion_perfil
  lifecycleCallbacks: {  }
