ExpEntrada:
    pattern:  /
    defaults: { _controller: ExpidianGlobalBundle:Default:index }

ExpInicio:
    pattern:  /inicio/
    defaults: { _controller: ExpidianGlobalBundle:Default:index }
    
ExpOrganismosList:
    pattern:  /organismos/
    defaults: { _controller: ExpidianGlobalBundle:Organismos:list }
    
ExpOrganismosNew:
    pattern:  /organismos/nuevo
    defaults: { _controller: ExpidianGlobalBundle:Organismos:new }

ExpOrganismosAjaxList:
    pattern:  /organismos/{page}
    defaults: { _controller: ExpidianGlobalBundle:Organismos:ajaxList, page: 1 }
    
ExpOrganismosEdit:
    pattern:  /organismos/{id_organismo}
    defaults: { _controller: ExpidianGlobalBundle:Organismos:edit }
 
 